### ISSUE TITLE
会ban机吗？

### ISSUE THREAD

**Issue by uaniheng** [CaiMiao/Tencent-switcher-GUI#1]

**Comment by CaiMiao** [comment]
会，行了吧

**Comment by SwimmingTiger** [comment]
腾讯和任天堂似乎每天进行一次数据同步，所以跨区的机器大概会在第二天被任天堂和腾讯的CDN拒绝连接（“2137-7403”错误），无法下载和更新游戏。不过eshop的封禁可能会晚一些，第二天可能还能登录eshop进行购买，但无法下载游戏（因为下载要走CDN）。大概在第三天，进eshop就会收到“2181-4008”错误（此主机已被任天堂限制使用网络服务）。

此外，不仅腾讯跨外服会被ban，外服跨腾讯也会被ban。似乎只要连接到与机器类型不匹配的CDN（腾讯或者非腾讯）就会被ban，不过这种ban不是即时的，类型不匹配的访问并不会马上被CDN拒绝，任天堂似乎是在后台用访问日志分析工具来慢慢找有问题的机器然后再ban。
